# Please make sure not abuse it
name: DownloadAndUpload
on:
  gollum
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Prepare your file
      run: |
        mkdir Download
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki/Home.md
        wget `cat $wiki | xargs` --directory-prefix=Download
    - name: Uploading
      run: |
        chmod -R 777 ./uploader/
        cat > ./uploader/auth.json <<EOF
        $token
        EOF
        ./uploader/OneDriveUploader -f -c "./uploader/auth.json" -skip -s "Download" -r "English"
      env: 
        token: ${{ secrets.TOKEN }}     
