# Please make sure not abuse it
name: DownloadAndUpload
on:
  gollum
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Prepare your file
      run: |
        mkdir Download
        sudo apt-get install transmission-cli
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki/Home.md

        cat > ./uploader/config.json <<EOF
        {
           "rpc-enabled": true,
           "peer-port" : 8443,
           "rpc-whitelist": "127.0.0.1",
           "speed-limit-down-enabled": true,
           "speed-limit-down": 7000,
           "speed-limit-up-enabled": true,
           "speed-limit-up": 10,
           "download-dir": "./uploader/down",
           "dht-enabled": false,
           "encryption": 0
        }
        EOF
        transmission-cli -g ./uploader/ "`cat $wiki | xargs`"
      env: 
        token: ${{ secrets.TOKEN }}     
#        wget `cat $wiki | xargs` --directory-prefix=Download
